<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>assets/app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
      <EmbeddedResource Include="assets/accessibility_color.png" />
      <EmbeddedResource Include="assets/airplane.png" />
      <EmbeddedResource Include="assets/alert.png" />
      <EmbeddedResource Include="assets/app_folder.png" />
      <EmbeddedResource Include="assets/app.ico" />
      <EmbeddedResource Include="assets/apps_add_in.png" />
      <EmbeddedResource Include="assets/apps_color.png" />
      <EmbeddedResource Include="assets/apps_list.png" />
      <EmbeddedResource Include="assets/archive_arrow_back.png" />
      <EmbeddedResource Include="assets/arrow_left.png" />
      <EmbeddedResource Include="assets/arrow_reset.png" />
      <EmbeddedResource Include="assets/arrow_square_up_right.png" />
      <EmbeddedResource Include="assets/autoplay.png" />
      <EmbeddedResource Include="assets/bluetooth_color.png" />
      <EmbeddedResource Include="assets/bluetooth.png" />
      <EmbeddedResource Include="assets/briefcase.png" />
      <EmbeddedResource Include="assets/brush_color.png" />
      <EmbeddedResource Include="assets/calendar_assistant.png" />
      <EmbeddedResource Include="assets/calendar_checkmark.png" />
      <EmbeddedResource Include="assets/calendar_check.png" />
      <EmbeddedResource Include="assets/calendar_clock.png" />
      <EmbeddedResource Include="assets/calendar_lock.png" />
      <EmbeddedResource Include="assets/calendar.png" />
      <EmbeddedResource Include="assets/call.png" />
      <EmbeddedResource Include="assets/camera.png" />
      <EmbeddedResource Include="assets/chat.png" />
      <EmbeddedResource Include="assets/checkmark_circle.png" />
      <EmbeddedResource Include="assets/chevron_right.png" />
      <EmbeddedResource Include="assets/circle_highlight.png" />
      <EmbeddedResource Include="assets/clipboard_paste.png" />
      <EmbeddedResource Include="assets/clipboard_task_list.png" />
      <EmbeddedResource Include="assets/clipboard_task.png" />
      <EmbeddedResource Include="assets/closed_caption.png" />
      <EmbeddedResource Include="assets/cloud.png" />
      <EmbeddedResource Include="assets/color.png" />
      <EmbeddedResource Include="assets/contrast.png" />
      <EmbeddedResource Include="assets/controller.png" />
      <EmbeddedResource Include="assets/credit_card_person.png" />
      <EmbeddedResource Include="assets/cursor.png" />
      <EmbeddedResource Include="assets/data_area.png" />
      <EmbeddedResource Include="assets/desktop_keyboard.png" />
      <EmbeddedResource Include="assets/desktop_speaker.png" />
      <EmbeddedResource Include="assets/dialpad.png" />
      <EmbeddedResource Include="assets/document.png" />
      <EmbeddedResource Include="assets/drawer_arrow_download.png" />
      <EmbeddedResource Include="assets/ear.png" />
      <EmbeddedResource Include="assets/eye_tracking.png" />
      <EmbeddedResource Include="assets/folder_document.png" />
      <EmbeddedResource Include="assets/globe_clock_color.png" />
      <EmbeddedResource Include="assets/globe_desktop.png" />
      <EmbeddedResource Include="assets/headset.png" />
      <EmbeddedResource Include="assets/history.png" />
      <EmbeddedResource Include="assets/home_color.png" />
      <EmbeddedResource Include="assets/hotspot.png" />
      <EmbeddedResource Include="assets/image_copy.png" />
      <EmbeddedResource Include="assets/image.png" />
      <EmbeddedResource Include="assets/info.png" />
      <EmbeddedResource Include="assets/keyboard.png" />
      <EmbeddedResource Include="assets/key.png" />
      <EmbeddedResource Include="assets/laptop_checkmark.png" />
      <EmbeddedResource Include="assets/laptop_color.png" />
      <EmbeddedResource Include="assets/laptop_multiple.png" />
      <EmbeddedResource Include="assets/laptop.png" />
      <EmbeddedResource Include="assets/local_language.png" />
      <EmbeddedResource Include="assets/locate_device.png" />
      <EmbeddedResource Include="assets/location_arrow.png" />
      <EmbeddedResource Include="assets/lock_closed.png" />
      <EmbeddedResource Include="assets/mail.png" />
      <EmbeddedResource Include="assets/map.png" />
      <EmbeddedResource Include="assets/mic.png" />
      <EmbeddedResource Include="assets/mic_record.png" />
      <EmbeddedResource Include="assets/more.png" />
      <EmbeddedResource Include="assets/mouse.png" />
      <EmbeddedResource Include="assets/music_note_play.png" />
      <EmbeddedResource Include="assets/new.png" />
      <EmbeddedResource Include="assets/paint_brush.png" />
      <EmbeddedResource Include="assets/panel_right_gallery.png" />
      <EmbeddedResource Include="assets/panel_separate_window.png" />
      <EmbeddedResource Include="assets/pen.png" />
      <EmbeddedResource Include="assets/people_list.png" />
      <EmbeddedResource Include="assets/people.png" />
      <EmbeddedResource Include="assets/person_add.png" />
      <EmbeddedResource Include="assets/person_color.png" />
      <EmbeddedResource Include="assets/person_heart.png" />
      <EmbeddedResource Include="assets/person_key.png" />
      <EmbeddedResource Include="assets/person.png" />
      <EmbeddedResource Include="assets/person_voice.png" />
      <EmbeddedResource Include="assets/phone_desktop.png" />
      <EmbeddedResource Include="assets/plug_connected.png" />
      <EmbeddedResource Include="assets/power.png" />
      <EmbeddedResource Include="assets/print.png" />
      <EmbeddedResource Include="assets/pulse_square.png" />
      <EmbeddedResource Include="assets/question_circle.png" />
      <EmbeddedResource Include="assets/radio.png" />
      <EmbeddedResource Include="assets/remote.png" />
      <EmbeddedResource Include="assets/reset.png" />
      <EmbeddedResource Include="assets/scan_type.png" />
      <EmbeddedResource Include="assets/search.png" />
      <EmbeddedResource Include="assets/search_square.png" />
      <EmbeddedResource Include="assets/server_link.png" />
      <EmbeddedResource Include="assets/share.png" />
      <EmbeddedResource Include="assets/shield_color.png" />
      <EmbeddedResource Include="assets/shield_keyhole.png" />
      <EmbeddedResource Include="assets/shield.png" />
      <EmbeddedResource Include="assets/slide_multiple.png" />
      <EmbeddedResource Include="assets/slide_text_person.png" />
      <EmbeddedResource Include="assets/sparkle_circle.png" />
      <EmbeddedResource Include="assets/sparkle.png" />
      <EmbeddedResource Include="assets/speaker.png" />
      <EmbeddedResource Include="assets/storage.png" />
      <EmbeddedResource Include="assets/table_settings.png" />
      <EmbeddedResource Include="assets/tablet_laptop.png" />
      <EmbeddedResource Include="assets/target.png" />
      <EmbeddedResource Include="assets/taskbar.png" />
      <EmbeddedResource Include="assets/text_font.png" />
      <EmbeddedResource Include="assets/touchpad.png" />
      <EmbeddedResource Include="assets/usb_stick.png" />
      <EmbeddedResource Include="assets/video_clip.png" />
      <EmbeddedResource Include="assets/video.png" />
      <EmbeddedResource Include="assets/virtual_network.png" />
      <EmbeddedResource Include="assets/wifi_color.png" />
      <EmbeddedResource Include="assets/wifi.png" />
      <EmbeddedResource Include="assets/wrench.png" />
      <EmbeddedResource Include="assets/wrench_screwdriver.png" />
      <EmbeddedResource Include="assets/zoom_in.png" />
  </ItemGroup>
</Project>
