<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon>assets/app.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
      <EmbeddedResource Include="assets/accessibility_color.svg" />
      <EmbeddedResource Include="assets/airplane.svg" />
      <EmbeddedResource Include="assets/alert.svg" />
      <EmbeddedResource Include="assets/app_folder.svg" />
      <EmbeddedResource Include="assets/app.ico" />
      <EmbeddedResource Include="assets/apps_add_in.svg" />
      <EmbeddedResource Include="assets/apps_color.svg" />
      <EmbeddedResource Include="assets/apps_list.svg" />
      <EmbeddedResource Include="assets/archive_arrow_back.svg" />
      <EmbeddedResource Include="assets/arrow_left.svg" />
      <EmbeddedResource Include="assets/arrow_reset.svg" />
      <EmbeddedResource Include="assets/arrow_square_up_right.svg" />
      <EmbeddedResource Include="assets/autoplay.svg" />
      <EmbeddedResource Include="assets/bluetooth_color.png" />
      <EmbeddedResource Include="assets/bluetooth.svg" />
      <EmbeddedResource Include="assets/briefcase.svg" />
      <EmbeddedResource Include="assets/brush_color.svg" />
      <EmbeddedResource Include="assets/calendar_assistant.svg" />
      <EmbeddedResource Include="assets/calendar_checkmark.svg" />
      <EmbeddedResource Include="assets/calendar_check.svg" />
      <EmbeddedResource Include="assets/calendar_lock.svg" />
      <EmbeddedResource Include="assets/calendar.svg" />
      <EmbeddedResource Include="assets/call.svg" />
      <EmbeddedResource Include="assets/camera.svg" />
      <EmbeddedResource Include="assets/chat.svg" />
      <EmbeddedResource Include="assets/checkmark_circle.svg" />
      <EmbeddedResource Include="assets/chevron_right.svg" />
      <EmbeddedResource Include="assets/circle_highlight.svg" />
      <EmbeddedResource Include="assets/clipboard_paste.svg" />
      <EmbeddedResource Include="assets/clipboard_task_list.svg" />
      <EmbeddedResource Include="assets/clipboard_task.svg" />
      <EmbeddedResource Include="assets/closed_caption.svg" />
      <EmbeddedResource Include="assets/cloud.svg" />
      <EmbeddedResource Include="assets/color.svg" />
      <EmbeddedResource Include="assets/contrast.svg" />
      <EmbeddedResource Include="assets/controller.svg" />
      <EmbeddedResource Include="assets/credit_card_person.svg" />
      <EmbeddedResource Include="assets/cursor.svg" />
      <EmbeddedResource Include="assets/data_area.svg" />
      <EmbeddedResource Include="assets/desktop_keyboard.svg" />
      <EmbeddedResource Include="assets/desktop_speaker.svg" />
      <EmbeddedResource Include="assets/dialpad.svg" />
      <EmbeddedResource Include="assets/document.svg" />
      <EmbeddedResource Include="assets/drawer_arrow_download.svg" />
      <EmbeddedResource Include="assets/ear.svg" />
      <EmbeddedResource Include="assets/eye_tracking.svg" />
      <EmbeddedResource Include="assets/folder_document.svg" />
      <EmbeddedResource Include="assets/globe_desktop.svg" />
      <EmbeddedResource Include="assets/headset.svg" />
      <EmbeddedResource Include="assets/history.svg" />
      <EmbeddedResource Include="assets/home_color.svg" />
      <EmbeddedResource Include="assets/hotspot.svg" />
      <EmbeddedResource Include="assets/image_copy.svg" />
      <EmbeddedResource Include="assets/image.svg" />
      <EmbeddedResource Include="assets/info.svg" />
      <EmbeddedResource Include="assets/keyboard.svg" />
      <EmbeddedResource Include="assets/key.svg" />
      <EmbeddedResource Include="assets/laptop_checkmark.svg" />
      <EmbeddedResource Include="assets/laptop_color.svg" />
      <EmbeddedResource Include="assets/laptop_multiple.svg" />
      <EmbeddedResource Include="assets/laptop.svg" />
      <EmbeddedResource Include="assets/locate_device.svg" />
      <EmbeddedResource Include="assets/location_arrow.svg" />
      <EmbeddedResource Include="assets/lock_closed.svg" />
      <EmbeddedResource Include="assets/mail.svg" />
      <EmbeddedResource Include="assets/map.svg" />
      <EmbeddedResource Include="assets/mic_record.svg" />
      <EmbeddedResource Include="assets/mic.svg" />
      <EmbeddedResource Include="assets/more.svg" />
      <EmbeddedResource Include="assets/mouse.svg" />
      <EmbeddedResource Include="assets/music_note_play.svg" />
      <EmbeddedResource Include="assets/paint_brush.svg" />
      <EmbeddedResource Include="assets/panel_right_gallery.svg" />
      <EmbeddedResource Include="assets/panel_separate_window.svg" />
      <EmbeddedResource Include="assets/pen.svg" />
      <EmbeddedResource Include="assets/people_list.svg" />
      <EmbeddedResource Include="assets/people.svg" />
      <EmbeddedResource Include="assets/person_add.svg" />
      <EmbeddedResource Include="assets/person_color.svg" />
      <EmbeddedResource Include="assets/person_heart.svg" />
      <EmbeddedResource Include="assets/person_key.svg" />
      <EmbeddedResource Include="assets/person.svg" />
      <EmbeddedResource Include="assets/person_voice.svg" />
      <EmbeddedResource Include="assets/phone_desktop.svg" />
      <EmbeddedResource Include="assets/plug_connected.svg" />
      <EmbeddedResource Include="assets/power.svg" />
      <EmbeddedResource Include="assets/print.svg" />
      <EmbeddedResource Include="assets/pulse_square.svg" />
      <EmbeddedResource Include="assets/question_circle.svg" />
      <EmbeddedResource Include="assets/radio.svg" />
      <EmbeddedResource Include="assets/remote.svg" />
      <EmbeddedResource Include="assets/reset.svg" />
      <EmbeddedResource Include="assets/scan_type.svg" />
      <EmbeddedResource Include="assets/search_square.svg" />
      <EmbeddedResource Include="assets/search.svg" />
      <EmbeddedResource Include="assets/server_link.svg" />
      <EmbeddedResource Include="assets/share.svg" />
      <EmbeddedResource Include="assets/shield_color.svg" />
      <EmbeddedResource Include="assets/shield_keyhole.svg" />
      <EmbeddedResource Include="assets/shield.svg" />
      <EmbeddedResource Include="assets/slide_multiple.svg" />
      <EmbeddedResource Include="assets/slide_text_person.svg" />
      <EmbeddedResource Include="assets/sparkle_circle.svg" />
      <EmbeddedResource Include="assets/sparkle.svg" />
      <EmbeddedResource Include="assets/speaker.svg" />
      <EmbeddedResource Include="assets/storage.svg" />
      <EmbeddedResource Include="assets/table_settings.svg" />
      <EmbeddedResource Include="assets/tablet_laptop.svg" />
      <EmbeddedResource Include="assets/target.svg" />
      <EmbeddedResource Include="assets/taskbar.svg" />
      <EmbeddedResource Include="assets/text_font.svg" />
      <EmbeddedResource Include="assets/touchpad.svg" />
      <EmbeddedResource Include="assets/usb_stick.svg" />
      <EmbeddedResource Include="assets/video_clip.svg" />
      <EmbeddedResource Include="assets/video.svg" />
      <EmbeddedResource Include="assets/virtual_network.svg" />
      <EmbeddedResource Include="assets/wifi_color.svg" />
      <EmbeddedResource Include="assets/wifi.svg" />
      <EmbeddedResource Include="assets/wrench_screwdriver.svg" />
      <EmbeddedResource Include="assets/wrench.svg" />
      <EmbeddedResource Include="assets/zoom_in.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Svg" Version="3.4.8" />
  </ItemGroup>
</Project>
