<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
      <EmbeddedResource Include="assets/accessibility_color.svg" />
      <EmbeddedResource Include="assets/apps_color.svg" />
      <EmbeddedResource Include="assets/arrow_left.svg" />
      <EmbeddedResource Include="assets/bluetooth_color.png" />
      <EmbeddedResource Include="assets/brush_color.svg" />
      <EmbeddedResource Include="assets/calendar_check.svg" />
      <EmbeddedResource Include="assets/chevron_right.svg" />
      <EmbeddedResource Include="assets/controller.svg" />
      <EmbeddedResource Include="assets/headset.svg" />
      <EmbeddedResource Include="assets/home_color.svg" />
      <EmbeddedResource Include="assets/laptop_color.svg" />
      <EmbeddedResource Include="assets/more.svg" />
      <EmbeddedResource Include="assets/person_color.svg" />
      <EmbeddedResource Include="assets/search_square.svg" />
      <EmbeddedResource Include="assets/shield_color.svg" />
      <EmbeddedResource Include="assets/storage.svg" />
      <EmbeddedResource Include="assets/wifi_color.svg" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Svg" Version="3.4.8" />
  </ItemGroup>
</Project>
